# Generated by Django 4.2 on 2023-04-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0004_profissao_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name_plural': 'Profissões'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
