# Generated by Django 4.2 on 2023-04-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0005_alter_profissao_options_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
    ]
