# Generated by Django 4.2 on 2023-04-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0010_remove_cliente_telefone_telefone_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='ddd',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
