# Generated by Django 4.2 on 2023-04-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0012_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='interesse',
            field=models.ManyToManyField(to='CadastroCliente.interesse'),
        ),
    ]
